%Making a cylinder
X = [pi/2,0;    pi/2, pi/2;     pi/2, pi;   pi/2, 3*pi/2;   0,0;    pi,0; ...
    atan(0.5), 0;  atan(0.5), pi/2; atan(0.5), pi;    atan(0.5), 3*pi/2; ...
    pi-atan(0.5), 0;  pi-atan(0.5), pi/2; pi-atan(0.5), pi;    pi-atan(0.5), 3*pi/2; ...
    atan(0.5), pi/4;  atan(0.5), 3*pi/4; atan(0.5), 5*pi/4;    atan(0.5), 7*pi/4; ...
    pi-atan(0.5), pi/4;  pi-atan(0.5), 3*pi/4; pi-atan(0.5), 5*pi/4;    pi-atan(0.5), 7*pi/4; ...
    atan(1), 0;  atan(1), pi/2; atan(1), pi;    atan(1), 3*pi/2; ...
    pi-atan(1), 0;  pi-atan(1), pi/2; pi-atan(1), pi;    pi-atan(1), 3*pi/2; ...
    atan(1), pi/4;  atan(1), 3*pi/4; atan(1), 5*pi/4;    atan(1), 7*pi/4; ...
    pi-atan(1), pi/4;  pi-atan(1), 3*pi/4; pi-atan(1), 5*pi/4;    pi-atan(1), 7*pi/4];

t = [1;1;1;1;2;2;sqrt(5);sqrt(5);sqrt(5);sqrt(5);sqrt(5);sqrt(5);sqrt(5);sqrt(5); ...
    sqrt(5);sqrt(5);sqrt(5);sqrt(5);sqrt(5);sqrt(5);sqrt(5);sqrt(5); ...
    sqrt(2);sqrt(2);sqrt(2);sqrt(2);sqrt(2);sqrt(2);sqrt(2);sqrt(2); ...
    sqrt(2);sqrt(2);sqrt(2);sqrt(2);sqrt(2);sqrt(2);sqrt(2);sqrt(2)];

%X gives (theta, phi) pairs: one per row
%t gives corresponding r values


n = 2; %Highest l used for spherical harmonics (ones from 0 to n will be used)
lam = 0.1; %Regularisation constant
res = 500; %Resolution for plotting shape

%Get the weights
%w = sc2sbf_lr(X, t, n, lam);
w = getweights_initial(X, t, n, lam);

%Plot the model of the shape and mark the training points
sbf_plot(w, X, t, n, res);